spring.datasource.url: jdbc:mysql://localhost:3306/search_engine
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: none
#server.servlet.context-path: /admin
user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
sites:
    siteList:
      -
          url: https://www.lenta.ru
          name: Лента.ру
      -
          url: http://radiomv.ru/
          name: Милицейская волна